config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'pages#show', page: "home_page"


  post "cards/" => "cards#create", as: :cards
  delete "cards/:id/" => "cards#destroy", as: :cards_destroy
  patch "cards/:id/" => "cards#update", as: :update_cards
  get "decks/:deck_id/cards/review" => "cards#review", as: :review_cards
  get "cards/cheat/" => "cards#cheat", as: :cheat


  get "decks/" => "decks#index", as: :decks
  get "decks/:id/edit/" => "decks#edit", as: :edit_decks #should this be singular?
  delete "decks/:id" => "decks#destroy", as: :destroy_decks
  patch "decks/:id" => "decks#update", as: :update_decks
  post "decks/" => "decks#create", as: nil #the name is repeated but its fine because the http verb is different, although it does not allow one to specify like this using as, it only allows one to indirectly do this, by daving the route be the same http://stackoverflow.com/questions/19189415/how-may-two-routes-with-different-http-request-types-share-the-same-name
  post "decks/upload" => "decks#upload", as: :upload_decks
  get "decks/download" => "decks#download", as: :download_csv

  get "pages/:page" => "pages#show", as: :pages

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck

  def self.to_csv
    CSV.generate(headers: true) do |csv|
     
      csv << ["question","answer","deck"]

      all.each do |card|
        csv << [card.question, card.answer, Deck.find(card.deck_id).name]
      end

    end 
  end


end

app/models/deck.rb
class Deck < ApplicationRecord
  def self.upload(file, current_user)
    CSV.foreach(file.path, headers: true) do |row|
      if Deck.where(name: row["deck"], user_id:current_user.id).exists?
        deck = Deck.where({name: row["deck"], user_id:current_user.id}).first
      else
        deck = Deck.create(name: row["deck"], user_id:current_user.id)
      end
      Card.create(row.to_hash.except("deck").update("deck_id" => deck.id))
    end
  end

  def mastery 
    collection = Card.includes(:deck).where(decks: {id: self.id })
    (collection.sum("current_ranking").to_f/(collection.count*5).to_f) * 100
  end

  has_many :cards
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:destroy, :update, :update_rank]
  before_action :authenticate_user!


  def create
    @card = Card.new(card_params)
    authorize @card
    respond_to do |format|
      if @card.save
        format.html { redirect_to :back, notice: "Card was successfully saved" }
      else
        format.html { render :back }
      end
    end
  end


  def cheat
    @cards = Card.includes(:deck).where(decks: { user_id: current_user.id})
  end


  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to(:back) } #not re rendering. Literally just clicking the back button
      else
        format.html { render :back }
      end
    end
  end


  def review
    @card = Card.includes(:deck).where(deck_id: review_params[:deck_id], decks: {user_id: current_user.id}).order(:current_ranking).first
    authorize @card
  end


  def destroy
    @card.destroy
    respond_to do |format| 
      format.html{ redirect_to :back, notice: "Successfully deleted card." }
    end
  end


  private

    def card_params
      params.require(:card).permit(:question,:answer,:current_ranking,:deck_id)
    end

    def set_card
      @card = Card.find(params[:id])
    end

    def review_params
      params.permit(:question,:answer,:current_ranking,:deck_id)
    end


end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:edit, :destroy, :update]
  before_action :authenticate_user!


  def upload
    Deck.upload(upload_params[:file], current_user)
    redirect_to :decks, notice: "Successfully uploaded CSV"
  end

  def index
  	@decks = current_user.decks
    @new_deck = Deck.new({user_id: current_user.id})
  end

  def edit
  	authorize @deck
  	@new_card = Card.new(deck_id:@deck.id)
  end

  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to :back }
      end
    end
  end

  def download
    @cards = Card.includes(:deck).where(decks: {user_id: current_user.id})
    respond_to do |format|
      format.csv { send_data @cards.to_csv }
    end
  end


  def create
    @deck = Deck.new(deck_params)
    authorize @deck
    respond_to do |format|
      if @deck.save
        format.html {redirect_to edit_decks_path(@deck), notice: "New deck created"}
      end
    end
  end


  def destroy
    authorize @deck
  	@deck.destroy
  	respond_to do |format|
      format.html { redirect_to :decks, notice: "Succesfully deleted deck." }
  	end
  end


  private
    def deck_params
      params.require(:deck).permit(:name, :user_id, :file)
    end

    def upload_params
      params.permit(:name, :user_id, :file)
    end
    
    def set_deck
      @deck = Deck.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
    	if params[:page] == "home_page"
    		if current_user
          redirect_to :decks
        else
    		  render template: "pages/#{params[:page]}", layout: false
    	  end
    	else
        render template: "pages/#{params[:page]}"
      end
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/cards/cheat.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "cards_cheat" %>
<% end %>




<%= react_component 'CheatPage', cards: @cards %>

app/views/cards/review.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "cards_review" %>
<% end %>


<div class="container" id="center-content" style="">
    <div id="deckName">
      <h3 class="text-left"><%= @card.deck.name %></h3>
    </div>
      <div class="card">
    <section class="question-card break-words">
      <p class="set-text">
        <%= @card.question %>
      </p>
    </section>
    
    <button class="btn btn-lg btn-primary btn-block" id="show-answer">Show Answer</button>
    
    <section class="question-card hide-it break-words" id="answer-card" style="border-top: 2px solid #d3d3d3;">
      <p style="margin-top:15px;" class="set-text">
        <%= @card.answer %>
      </p>
    </section>
    <p class="text-center hide-it" style="color:#cccccc;" id="how-well">How easily did you recall this answer?<%= link_to raw('&nbsp;Edit'), edit_decks_path(@card.deck), style: "text-decoration:none;background:none;color:black;" %></p>
    <section id="fixed-bottom">
      <div class="btn-group hide-it" id="recall-rank">

        <%= form_for @card, url: update_cards_path(@card), html: {class:"btn-group", style: "width:20%;color:white;"} do |f| %>
          <%= f.hidden_field :current_ranking, value:1 %><%= f.hidden_field :deck_id %>
          <%= f.submit "1", class:"btn btn-danger btn-lg btn-block", style:"border-bottom-left-radius: 3px;border-top-left-radius: 3px;" %>
        <% end %>
        <%= form_for @card, url: update_cards_path(@card), html: {class:"btn-group", style: "width:20%;color:white;"} do |f| %>
          <%= f.hidden_field :current_ranking, value:2 %><%= f.hidden_field :deck_id %>
          <%= f.submit "2", class:"btn btn-warning btn-lg btn-block" %>
        <% end %>
        <%= form_for @card, url: update_cards_path(@card), html: {class:"btn-group", style: "width:20%;color:white;"} do |f| %>
          <%= f.hidden_field :current_ranking, value:3 %><%= f.hidden_field :deck_id %>
          <%= f.submit "3", class:"btn btn-info btn-lg btn-block" %>
        <% end %>
        <%= form_for @card, url: update_cards_path(@card), html: {class:"btn-group", style: "width:20%;color:white;"} do |f| %>
          <%= f.hidden_field :current_ranking, value:4 %><%= f.hidden_field :deck_id %>
          <%= f.submit "4", class:"btn btn-success btn-lg btn-block" %>
        <% end %>
        <%= form_for @card, url: update_cards_path(@card), html: {class:"btn-group", style: "width:20%;color:white;"} do |f| %>
          <%= f.hidden_field :current_ranking, value:5 %><%= f.hidden_field :deck_id %>
          <%= f.submit "5", class:"btn btn-primary btn-lg btn-block" %>
        <% end %>

      </div>
    </section>
  </div>
</div>




<script>
$("#show-answer").click(function(){
  $("#recall-rank").show()
  $("#how-well").show()
  $("#answer-card").show()
  $("#show-answer").hide()
})
</script>

app/views/decks/edit.html.erb
<%= csrf_meta_tag %>

<style>
  #deck-name:hover {
    background:#e8e8e8;
  }  
  #deck-name:focus {
    background:#e8e8e8;
  }
  textarea {
    width:100%;
  }
  .table-header {
    font-weight:700;
  }
</style>

<section class="col-md-12">
  <h3 style="display:inline-block;"><span id="deck-name" contenteditable="true"><%= @deck.name %></span></h3>
  <%= link_to "Delete Deck", destroy_decks_path(@deck), method: :delete, class: "btn btn-warning", style: "float:right;color:white;", data: { confirm: 'Are you sure?' } %>


  <div class="row" style="border-bottom: 2px solid #d5d5d5;padding:12px 8px 3px;margin-top:20px;">
    <div class="col-xs-5 table-header">
      <span>Question</span>

    </div>
    <div class="col-xs-5 table-header">
      <span>Answer</span>


    </div>
    <div class="col-xs-2 table-header text-center">
      <span>Action</span>


    </div>    
  </div>


    <% @deck.cards.each do |card| %>
      <%= form_for(card, url: update_cards_path(card)) do |f| %>
      <% if card.errors.any? %>
        <% card.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
    <div class="row" style="border-top: 1px solid #d5d5d5;padding:12px 8px 3px;">
      <div class="col-xs-5">
        <%= f.text_area :question %>
      </div>
      <div class="col-xs-5">
        <%= f.text_area :answer %>  
      </div>
      <div class="col-xs-2 text-center">
          <div class="btn-group btn-group-horizontal" role="group" aria-label="...">

          <%= button_tag(type: 'submit', class: "btn btn-success") do %>
            <i  class="glyphicon glyphicon-floppy-disk"></i>
          <% end %>        
          <%= link_to raw('<i style="color:white;" class="glyphicon glyphicon-trash"></i>'), cards_destroy_path(card), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
      <% end %>
    <% end %>


    <%= form_for(@new_card) do |f| %>
      <% if @new_card.errors.any? %>
        <% @new_card.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

    <div class="row" style="border-top: 1px solid #d5d5d5;padding:12px 8px 3px;">
      <div class="col-xs-5">
        <%= f.text_area :question %><%= f.hidden_field :deck_id %>
      </div>
      <div class="col-xs-5">
        <%= f.text_area :answer %>
      </div>
      <div class="col-xs-2 text-center">
        <div class="btn-group btn-group-horizontal" role="group" aria-label="...">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            <i  class="glyphicon glyphicon-floppy-disk"></i> Save New
          <% end %>        
        </div>
      </div>
    </div>
    <% end %>



  </div>

</section>



<script>



$("#deck-name").blur(function(el){
  console.log(el)
  $.ajax({
    url: '<%= update_decks_path(@deck) %>', 
    data : JSON.stringify({ name: !!el.target.innerText ? el.target.innerText : "Deck Name", authenticity_token: $('meta[name=csrf-token]').attr('content') }),
    type : 'PATCH',
    contentType : 'application/json',
    processData: false,
    dataType: 'json'
  })
})

</script>

app/views/decks/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "decks_index" %> 
<% end %>



  <section class="col-md-8 col-md-offset-2">
    <h3 class="text-center">My Decks</h3>
   
    <div class="row" style="border-bottom: 2px solid #d5d5d5;padding:12px 8px 3px;margin-top:20px;">
      <div class="col-xs-3">
        <span class="table-header">Deck</span>
      </div>
      <div class="col-xs-3">
       <span class="table-header">Mastery</span>
      </div>
      <div class="col-xs-3">
       <span class="table-header">Cards</span>
      </div>
      <div class="col-xs-3 text-center">
        <button class="btn btn-sm btn-success dropdown-toggle" type="button" data-toggle="dropdown">
          <span class="glyphicon glyphicon-plus"></span>
        </button>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a onclick='$(".hidden-form").slideDown("slow")' href="javascript:void(0);"><i class="glyphicon glyphicon-plus ex"></i><span class="hide-deck"> Create New Deck</span></a></li>
              <li><a onclick='document.querySelector("#file").click()' href="javascript:void(0);"><i class="glyphicon glyphicon-open-file"></i><span> Upload CSV</span></a></li>
               <li><%= link_to raw('<i class="glyphicon glyphicon-save-file"></i><span> Download CSV</span>'), download_csv_path(format: "csv") %></li>
            </ul>
      </div>
    </div>



    <div class="row hidden-form" style="border-top: 1px solid #d5d5d5;padding:6px 8px 6px;display:none;">

    <%= form_for(@new_deck) do |f| %>
    <div class="col-xs-3" style="padding-top:4px;">
      <%= f.text_field :name %><%= f.hidden_field :user_id %>
    </div>
    <div class="col-xs-3" style="padding-top:4px;">
     <span class="">0%</span>
    </div>
    <div class="col-xs-3" style="padding-top:4px;">
     <span class="">0</span>
    </div>
    <div class="col-xs-3 text-center">
      <%= f.submit :Save, class: "btn btn-primary btn-sm" %>
    </div>

    <% end %>

    </div>


    <% @decks.each do |deck| %> 


    <div class="row deck-row" style="border-top: 1px solid #d5d5d5;padding:6px 8px 6px;">
      <div class="col-xs-3" style="padding-top:4px;">
        <span class=""><%= deck.name %></span>
      </div>
      <div class="col-xs-3" style="padding-top:4px;">
       <span class=""><%= number_to_percentage deck.mastery, precision: 0 %></span>
      </div>
      <div class="col-xs-3" style="padding-top:4px;">
       <span class=""><%= deck.cards.count %></span>
      </div>
      <div class="col-xs-3 text-center">
          <p class="btn-group" style="margin:0;">
          <%= link_to raw('<i style="color:black;" class="glyphicon glyphicon-eye-open"></i>'), review_cards_path(deck.id), style: "color:white;border-radius:3px !important;", class: "btn btn-default btn-sm btn-edges" %>
          
          
          <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_decks_path(deck), class:"btn btn-warning btn-sm btn-edges", style: "border-radius:3px !important;color:white;" %>
        </p>
      </div>
    </div>
    <% end %>
  


  </section>


<%= form_tag upload_decks_path, multipart: true, method: :post, style: "display:none;", id: "upload_form" do %>
<%= file_field_tag :file, onchange: "this.form.submit()" %>
<% end %>



<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Srs</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
	  <meta name="description" content="">
	  <meta name="author" content="">
	  <link rel="icon" href="../../favicon.ico">
	  <title>Spaced Repetition For All</title>
	  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="http://bigintro.pythonanywhere.com/static/cards/bootstrap.css">
	  <link rel="stylesheet" type="text/css" href="http://bigintro.pythonanywhere.com/static/cards/styles.css">
	  <link rel="stylesheet" type="text/css" href='http://bigintro.pythonanywhere.com/static/cards/responsive.css'>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= yield :head %>

  </head>

  <body>
	    <nav class="navbar navbar-inverse navbar-static-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="/">Simple<span style="font-weight:700;">SRS</span></a>
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
	          <ul class="nav navbar-nav navbar-right">
	            <% if user_signed_in? %>
<!-- 	              <li><%= link_to "About", pages_path(page:"about") %></li>
 -->	          <li><%= link_to "Search", cheat_path %></li>
	              <li><%= link_to "My Decks", decks_path %></li>

	              <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">
                      <%= current_user.email[0,current_user.email.index("@")] %> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="themes">
                      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>

                <% else %>
<!-- 	              <li><a href="/pages/about">About</a></li>
 -->	           <li><%= link_to "Log In", new_user_session_path %></li>
	              <li><%= link_to "Sign Up", new_user_registration_path %></li>
	            <% end %>
	          </ul>
	        </div>
	      </div>
	    </nav>
    <div class="container content">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>


<!--       <% if notice %>
		<div class="alert alert-dismissible alert-success">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <p><%= notice %></p>
		</div>
      <% end %>
      <% if alert %>
		<div class="alert alert-dismissible alert-warning">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <p><%= alert %></p>
		</div>
      <% end %> -->

      <%= yield %>


    </div>
  
  <div class="footer"><span style="color:grey;font-size:0.8em;">SimpleSRS: Simple SRS For All</span></div>
 
  <script src="https://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript"></script>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", "data-turbolinks-eval" => false %>
  <script src="/static/cards/responsive.js" type="text/javascript"></script>
  </body>
</html>

app/views/pages/home_page.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="A free, open source, cross platform, easy to use spaced repetition app">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Spaced Repitition for All</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://bigintro.pythonanywhere.com/static/cards/workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://bigintro.pythonanywhere.com/static/cards/cover.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Simple<span style="font-weight:700;">SRS</span></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Simple SRS for All</h1>
            <p class="lead">Free, Intuitive, and Responsive access to Spaced Repetition Software for everyone.</p>
            <p class="lead">
              <a href="https://youtu.be/PbAEjyDomIk" class="btn btn-lg btn-default">Watch a Video</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Fork us on <a href='#'>github</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js" type="text/javascript"></script>
  </body>
</html>

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="A free, open source, cross platform, easy to use spaced repetition app">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Spaced Repitition for All</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://bigintro.pythonanywhere.com/static/cards/workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://bigintro.pythonanywhere.com/static/cards/cover.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Simple<span style="font-weight:700;">SRS</span></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><%= link_to "Login", new_user_session_path %></li>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Simple SRS for All</h1>
            <p class="lead">Free, Intuitive, and Responsive access to Spaced Repetition Software for everyone.</p>
            <p class="lead">
              <a href="https://youtu.be/PbAEjyDomIk" class="btn btn-lg btn-default">Watch a Video</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Fork us on <a href='https://github.com/introbig/srs'>github</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js" type="text/javascript"></script>
  </body>
</html>